version: '3'

services:

  nginx:
    build:
      context: ./nginx/
      args:
        - PGID=${PGID}
        - PUID=${PUID}
    volumes:
      - ../../:/var/www
      - ./nginx/logs:/var/log/nginx
      - ./nginx/sites:/etc/nginx/conf.d
    ports:
      - "80:80"
    links:
      - php-fpm
    networks:
      - default

  php-fpm:
    build:
      context: ./php-fpm/
      args:
        - PGID=${PGID}
        - PUID=${PUID}
        - PHP_VERSION=${PHP_VERSION}
        - PHP_INI_ENVIRONMENT=${PHP_INI_ENVIRONMENT}
        - INSTALL_APCU=${INSTALL_APCU}
        - INSTALL_BCMATH=${INSTALL_BCMATH}
        - INSTALL_GD=${INSTALL_GD}
        - INSTALL_INTL=${INSTALL_INTL}
        - INSTALL_MEMCACHED=${INSTALL_MEMCACHED}
        - INSTALL_MONGO=${INSTALL_MONGO}
        - INSTALL_MYSQL=${INSTALL_MYSQL}
        - INSTALL_OPCACHE=${INSTALL_OPCACHE}
        - INSTALL_PGSQL=${INSTALL_PGSQL}
        - INSTALL_PHPREDIS=${INSTALL_PHPREDIS}
        - INSTALL_SOAP=${INSTALL_SOAP}
        - INSTALL_SQLITE=${INSTALL_SQLITE}
        - INSTALL_TOKENIZER=${INSTALL_TOKENIZER}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - INSTALL_ZIP=${INSTALL_ZIP}
        - INSTALL_PHALCON_FRAMEWORK=${INSTALL_PHALCON_FRAMEWORK}
        - PHALCON_FRAMEWORK_VERSION=${PHALCON_FRAMEWORK_VERSION}
    volumes:
      - ../../:/var/www
    expose:
      - "9000"
    networks:
      - default

  redis:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      - default

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=tcommerce
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=tcommerce
      - MYSQL_PASSWORD=tcommerce
    volumes:
      - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default

networks:
  default:
    driver: "bridge"